excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://zacck.github.io
title: Learnist Journey
tagline: A log of everyday life
description: Hi guys my name is Zacck, I like learning stuff and tinkering with stuff. Welcome to my Journey feel free to come with me.
paginate: 5